### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by martint17r** [Hellspam/goharproxy#1]
Hi,

could you please state the license under which this project is open sourced?

Cheers

Martin

**Comment by Hellspam** [comment]
Hi Martin,
Haven't really thought about it, as I haven't worked on this project in a
while (unfortunately, I didn't have time to really dive in and implement
all of browsermob proxies features, so I decided to keep using browsermob
for the time being)
I can put it at whatever license you'd like.

Thanks,
Roy Arnon

**Comment by martint17r** [comment]
I would prefer an open one, i.e. MIT License or the Go License.

Cheers

Martin

**Comment by Hellspam** [comment]
Added license
